<a href="https://colab.research.google.com/github/Abuelias2020/lab-1/blob/main/Python_Scratchbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
name = ["a","b"]

print(name)

['a', 'b']


In [2]:
print(len(name))

2


In [3]:
name.append("c")

print(name)

['a', 'b', 'c']


In [4]:
import numpy as np

name_array = np.array(name)

print(name_array)

['a' 'b' 'c']


In [6]:
print(type(name_array))

<class 'numpy.ndarray'>


In [9]:
x= [1,2,4,5]

print(type(x))

my_numbers = np.array(x)

print(type(my_numbers))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
my_numbers[1]

2

In [11]:
my_2d_array = np.array([[1,2,3],
                        [10,20,30],
                        [99,98,97]])

print(my_2d_array)

[[ 1  2  3]
 [10 20 30]
 [99 98 97]]


In [12]:
test = np.array([[1,2,3]])

print(test)

[[1 2 3]]


In [13]:
print(my_2d_array.shape)

(3, 3)


In [14]:
print(test.shape)

(1, 3)


In [16]:
print(my_2d_array.ndim)

2


In [17]:
students = {"student1":90,"Student2":87,"student3":100}

print(students)

{'student1': 90, 'Student2': 87, 'student3': 100}


In [18]:
my_dict = {20}

In [19]:
my_dict

{20}

In [21]:
students.values()

dict_values([90, 87, 100])

In [23]:
my_2d_array[0,:]

array([1, 2, 3])

In [24]:
my_2d_array[:,1]

array([ 2, 20, 98])

In [26]:
import pandas as pd

my_df = pd.DataFrame(my_2d_array,columns=['Student 1','Student 2','Student 3'])

my_df

Student 1  Student 2  Student 3
0          1          2          3
1         10         20         30
2         99         98         97

In [29]:
my_df['Student 1']

0     1
1    10
2    99
Name: Student 1, dtype: int64

In [30]:
my_df[["Student 1","Student 3"]]

Student 1  Student 3
0          1          3
1         10         30
2         99         97

In [31]:
my_df.loc[:,'Student 1']

0     1
1    10
2    99
Name: Student 1, dtype: int64

In [36]:
my_df.iloc[0,2]

3

In [38]:
my_df.loc[1,"Student 1"]

10

In [46]:
scores = [98,96,94,99,90,89]

my_number = [1,2,3,4,5,6]

for i in my_number:
  print(f"My number is {i} and the score is {scores[i-1]}")


My number is 1 and the score is 98
My number is 2 and the score is 96
My number is 3 and the score is 94
My number is 4 and the score is 99
My number is 5 and the score is 90
My number is 6 and the score is 89


In [45]:
x = 100

print(f"My number is {x}")

My number is 100


In [ ]:
from sklearn.tree import plot_tree

plot_tree(dt,feature_names = df.columns)


import matplotlib.pyplot as plt

plt.savefig('MyTree.png')